### ISSUE TITLE
Last row is not displayed

### ISSUE THREAD

**Issue by thsnr** [antonmedv/red#4]
### Summary

The last row of input logs is not displayed.

I suspect that this is an off-by-one error caused by https://github.com/antonmedv/red/blob/2cbbaaf33bd4e3165505927fe0f26723b03bac92/main.go#L159-L160

`row` is a 1-based index, so the termination condition should be `row <= store.Len()`.

### red version

2cbbaaf33bd4e3165505927fe0f26723b03bac92

### Steps to reproduce

```
$ echo '{"message": "I am a message"}' | red message
```

```
$ echo '{"message": "I am a message"}{"message": "Second message"}' | red message
```

### Expected behavior

The first command should display one row ("I am a message") and the second should display two rows ("I am a message" and "Second message").

### Actual behavior

The first command displays nothing, the second command only displays "I am a message".

**Comment by antonmedv** [comment]
You are right! Thanks.

Can you create PR? Or I'll fix it later today.

**Comment by hitzhangjie** [comment]
maybe it's ComputeDistance's problem.

**Comment by hitzhangjie** [comment]
My test case is :
while [ 1 -eq 1 ]; do ts=`date +"%F %T"`; echo {\"time\": \"$ts\", \"level\":\"info\", \"msg\": \"hello world, golang\"} >> 1.log; sleep 1; done
while [ 1 -eq 1 ]; do ts=`date +"%F %T"`; echo {\"time\": \"$ts\", \"level\":\"error\", \"msg\": \"hello world, javascript\"} >> 1.log; sleep 2; done
while [ 1 -eq 1 ]; do ts=`date +"%F %T"`; echo {\"time\": \"$ts\", \"level\":\"error\", \"msg\": \"hello world, cc++\"} >> 1.log; sleep 2; done

it can display all 3 logging messages, while I change the last loglevel from debug to error, it doesn't, only two lines ouput.
![image](https://user-images.githubusercontent.com/3725760/55051664-243d7c00-5091-11e9-9514-d8f7dbb29ed9.png)

**Comment by thsnr** [comment]
> it can display all 3 logging messages, while I change the last loglevel from debug to error, it doesn't, only two lines ouput.

Note that distance is computed based on space-separated words (with short keys, e.g., "debug", counting as double). And by default all messages with distance less than 3 are grouped together. So

```
debug debug hello world, cc++
error error hello world, javascript
```

are not grouped together (distance 3) while

```
error error hello world, cc++
error error hello world, javascript
```

are (distance 1).
