### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by ye** [antonmedv/red#7]
The `go get github.com/antonmedv/red` method didn't work on my macOS mojave

![Screen Shot 2019-03-26 at 1 00 03 PM](https://user-images.githubusercontent.com/133924/55017550-5aaec480-4fc7-11e9-8124-d332c5ac5a30.png)

**Comment by ye** [comment]
It could be [an upstream issue](https://github.com/rivo/tview/issues/205) that a version pin needs to happend somewhere, at the interim can some one make binary releases please?

**Comment by antonmedv** [comment]
Will do.

**Comment by ye** [comment]
Related to #3 sorry about making a duplicate (I actually I forgot I filed a ticket already a few days ago.) closing this.

**Comment by ye** [comment]
FYI, with a `-u` flag, "go get" works.

`go get -u github.com/antonmedv/red`
